set nocompatible                " be iMproved

"  ---------------------------------------------------------------------------
"  Plugins
"  ---------------------------------------------------------------------------


silent! runtime bundles.vim
 
""" User interface {{{
    """ Syntax highlighting {{{
        filetype plugin indent on                   " detect file plugin+indent
        syntax on                                   " syntax highlighting
        set background=dark                         " we're using a dark bg
        colorscheme jellybeans                      " colorscheme from plugin
        """ .txt w/highlight, plaintex is useless, markdown for .md {{{
            augroup FileTypeRules
                autocmd!
                autocmd BufNewFile,BufRead *.txt set ft=sh tw=79
                autocmd BufNewFile,BufRead *.tex set ft=tex tw=79
                autocmd BufNewFile,BufRead *.md set ft=markdown tw=79
            augroup END
        """ }}}
        """ 256 colors for maximum jellybeans bling. {{{
            if (&term =~ "xterm") || (&term =~ "screen")
                set t_Co=256
            endif
        """ }}}
    """ }}}
""" }}}

" allow Vim to manage multiple buffers effectively
set hidden

" keep a longer history
set history=1000

" enable extended % matching
runtime macros/matchit.vim

" make file/command completion useful
set wildmenu
set wildmode=list:longest

" use case-smart searching
set ignorecase
set smartcase

" set the terminal title
set title

" maintain more context around the cursor
set scrolloff=3

" enable limited line numbering
set ruler

" catch trailing whitespace
set listchars=tab:>-,trail:·,eol:$
nmap <silent> <leader>s :set nolist!<CR>

set autoindent
set expandtab
set shiftwidth=4
set softtabstop=4
set pastetoggle=<F2>
